### ISSUE TITLE
🐞[Bug]: Overflow Milestones Progress cards items

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [recodehive/machine-learning-repos#1531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the repository statistics section of the Milestones Progress cards, all models and tools representing the color are overflowing from the cards.

### Add ScreenShots

![overflow-cards-in](https://github.com/user-attachments/assets/54d75d14-b42a-4dd5-aef0-416673e2a002)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CGaneshKumar2002** [comment]
Hi @sanjay-kv, If this issue is unassigned, I'd love to contribute to this one. Thanks

**Comment by CGaneshKumar2002** [comment]
Hey @biswajit-sarkar-007 I'd appreciate if you provide me with some steps to replicate this issue because I'm only seeing blank space there. I'm new to this project and I will be glad to contribute to this one.

![image](https://github.com/user-attachments/assets/6eea0479-36ae-4df1-b3d9-54ed160e03a4)

**Comment by CGaneshKumar2002** [comment]
Hi @sanjay-kv, Raised a PR for this one. Kindly go through this and I'd appreciate your valuable feedback if there's any. Thanks!
