### ISSUE TITLE
Add Parkinson detection based on sketches and deep learning 

### ISSUE THREAD

**Issue by ananyag309** [recodehive/machine-learning-repos#768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Parkinson's disease is a brain disorder that causes unintended or uncontrollable movements, such as shaking, stiffness, and difficulty with balance and coordination. Traditionally, to detect Parkinson MRI images are used.

### Suggested Change

You can access to dataset from (https://www.kaggle.com/datasets/kmader/parkinsons-drawings).

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanjay-kv** [comment]
I will be assigned 2 of your issue level 3, so you can match 150 score faster. 
Will removing extra score above limitation from code harbour

**Comment by ananyag309** [comment]
@sanjay-kv sir my total pr points count is coming 1455 where 90 points are from this repo. u gave me two issue of 45 points which make  180 points from this repo i.e. 30 extra points so my current score on leaderboard should be 1455-30 = 1425 but its around 1295 ??? i am really confused and worried please help me out

**Comment by ananyag309** [comment]
also my yesterday score was 1425 with 91 pr and it is 1295 with 94 pr @sanjay-kv sir please help me out

**Comment by sanjay-kv** [comment]
[screencapture-life-made-easy-vercel-app-2024-07-17-15_33_42.pdf](https://github.com/user-attachments/files/16260666/screencapture-life-made-easy-vercel-app-2024-07-17-15_33_42.pdf)


This is you current score from everywhere, 

you have done few spams which will be removed eventually. so i dont see any confusion. The data i gave above is directly pulled from the github

**Comment by ananyag309** [comment]
@sanjay-kv  sir when my pull req was merged they told the highest score could be 200 in each repo someone told me 180 so accordingly i raised the issue, and it is fine to me if from now only 150 points from each repo will be counted but why only my score is removed most of the other contributors have even more than 250+ score in a single repo for example - someone on rank 16 has 1600 points on a single repo - if the score is modified it should be modified for all contributors on the same time or I should too have my last score on leaderboard, this is just one example there are even more contributors, please have a check too it

**Comment by sanjay-kv** [comment]
Hi @ananyag309 you are getting few things completely wrong. 
1st we released guidelines to make this clear, https://github.com/GSSoC24/Contributor/tree/main/gssoc-guidelines 
Guidelines has been communicated via mails , discord, newsletter and Linkedin announcment. so cant say never knew about . 
Guidelines released on 10th June. 

![image](https://github.com/user-attachments/assets/53c96f30-530b-4114-afc5-dc3ca7008062)

This clearly says the highlighted repo 150 points apply when you do documentation, beyond that its possible for to score on that particular repo. if you contribute technical works. such as fixing a broken website button, fixing nav bar issue something like hat. 

Score for all top 35 contributors has been reviewed and reduced 2 weeks back. im on the process of doing that right now. 
https://github.com/GSSoC24/Contributor/discussions/490
https://github.com/GSSoC24/Contributor/discussions/492

you can see the respective disscussion on the same here, so we are doing it, you may find spams kindly report in the discussion form with their PR link. It might take some time. because Program is huge. 
Let me know if anything i can help.

regarding 200 points there were people who did 800 900 poits on documentation for them we mentioned 200 points will be awarded rest of them only 150 points going forward.

**Comment by sanjay-kv** [comment]
I will keep 200 points on few repos for you

**Comment by ananyag309** [comment]
ok sir thank you I started contributing for the program in june itself, i was totally new i didn't go through the guidelines, it was bad on my side. also one more thing if i added some projects or enhanced feature instead of feature req i did it in doc update while raising issue will it to be a problem?

**Comment by sanjay-kv** [comment]
if there is any technical work limitation doesnt apply
